# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df08df7bf6960f3081f550166d0dd4b9417032369f553abb46a1d2eb25304393af39a37de2ffd938b55cc3210b1b81d031f493d08b15f5af672f56bdc7f5f5a7

test:
  secret_key_base: 915c3629906333c1ef3fa7d7a7f5f2fdf0d17becc688c7ee32cdb06773c1ef1102e9b4bbcf95592e125a84cbb70f80af3e8cba3cfcec78131243cdab6c83ff77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
